template = ""
rev_id = 5
template_sha = "b1bcc12f5675c5b86f53da0a290c53417f28d6e3"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "smn"
__UND2C_TRG__ = "se"
__UNDEFINED_SOURCE__ = "Inari Saami"
__UNDEFINED_TARGET__ = "North Saami"
__UND_SRC__ = "smn"
__UND_TRG__ = "sme"
