remote_theme: giellalt/jekyll-theme-giellalt@main
title: Dictionary for Inari Saami ⇒ North Saami
description: An electronic dictionary from Inari Saami to North Saami
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji

defaults:
  - scope: { path: "" }
    values:
      layout: default
