theme: jekyll-theme-giellalt
title: Dictionary for Inari Saami ⇒ North Saami
description: An electronic dictionary from Inari Saami to North Saami

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
